// THEME COLORS
const PRIMARY_COLOR = '#019592'
const PRIMARY_COLOR_LIGHT = '#e5f4f4'
const PRIMARY_COLOR_DISABLED = '#b2dfde'

// OTHER COLORS
const BLACK = '#212121'
const RED = '#f44336'

export const COLORS = {
    PRIMARY_COLOR,
    PRIMARY_COLOR_LIGHT,
    PRIMARY_COLOR_DISABLED,
    BLACK,
    RED
}
